import type {Metadata} from "next";
import {Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import React from "react";

const plusJakartaSans = Plus_Jakarta_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "PowerUP",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={"scroll-smooth"}>
      <body className={plusJakartaSans.className + " bg-background"}>
      {children}
      </body>
      </html>
  );
}
